' THIS IS A TEMPORARY FILE
@startuml Store Supply Order Approval Flow
start
title Store Supply Order Approval Flow
switch (Check if Order is Delayed)
case (Create a Case)
#F97924:<color:white><size:30><&menu></size>;
floating note left
**Set Order Name**
Assignment
end note
#F9548A:<color:white><size:30><&medical-cross></size>;
floating note left
**Create Case**
Create Records
end note

case (No Case Needed)
endswitch
switch (Check Order Amount)
case (Approval Needed)
#344568:<color:white><size:30><&pulse></size>;
floating note left
**Submit for Approval**
Action
end note

case (No Approval Needed)
endswitch
stop
@enduml