' THIS IS A TEMPORARY FILE
@startuml New Order Email to Supplier
start
title New Order Email to Supplier
floating note left: Loop_through_Suppliers
 repeat :<size:30><&loop-circular></size>;
#F97924:<color:white><size:30><&menu></size>;
floating note left
**Thank You Message**
Assignment
end note
#344568:<color:white><size:30><&pulse></size>;
floating note left
**Send Email to Supplier**
Action
end note
repeat while (more data?)
stop
@enduml